name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 1f744718-97c5-4217-8b0f-a7a84884c905
          SONAR_TOKEN: 6c6b2469c3347bcc5a90cd7dbec5c8ce8a816eb6
        args: >-
          -Dsonar.projectKey=examly-test_1f744718-97c5-4217-8b0f-a7a84884c905
          -Dsonar.organization=examly-test -Dsonar.sources= -Dsonar.verbose=true
